CREATE TABLE skill_upload_requests (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    token_hash CHAR(64) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    agent_id BIGINT NOT NULL,
    repository_id BIGINT NULL,
    skill_name VARCHAR(64) NOT NULL,
    version VARCHAR(50) NOT NULL,
    description VARCHAR(50) NOT NULL,
    tags VARCHAR(500) NOT NULL,
    category VARCHAR(100) NULL,
    type VARCHAR(50) NULL,
    expected_commit CHAR(40) NOT NULL,
    manifest_json JSON NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    expires_at DATETIME NOT NULL,
    decided_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_skill_upload_request_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_skill_upload_request_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
    CONSTRAINT fk_skill_upload_request_repo FOREIGN KEY (repository_id) REFERENCES skill_repositories(id) ON DELETE SET NULL,
    INDEX idx_skill_upload_request_owner (agent_id, status),
    INDEX idx_skill_upload_request_expiry (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
